name: Deploy Django App to Azure

on:
  push:
    branches:
      - main  # Or your default branch

env:
  AZURE_WEBAPP_NAME: test-app13            # 👈 Replace with your App Service name
  AZURE_WEBAPP_PACKAGE_PATH: './login'              # Root folder
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collectstatic (optional)
        run: |
          python manage.py collectstatic --noinput

      - name: Zip application
        run: zip -r app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./app.zip
