name: Deploy Django OTP App to Azure

on:
  push:
    branches:
      - main  # Change this if your default branch is something else

env:
  AZURE_WEBAPP_NAME: test-app13                 # 👈 Replace with your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: './login/login'   # 👈 Actual location of manage.py
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python manage.py collectstatic --noinput

      - name: Zip application folder
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          zip -r ../app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./app.zip
